# -*- coding: utf-8 -*-
"""WD 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZfVF_ABfaoy2iIdO5oBl7ZJK4WcSLmWs
"""

5678+7654+6780

print ('hello coders')

#K(#Keywords
#(for,while,True,def,int,str,set,dict)
#I (Identifier -  

a = 1
def sum(a,b):
  apple = 78

  class plots()

#identifier(to whom we assign a values like variable,class or object etc)

#literals(values assigned to a variable or identifier)

#operators(which links identifiers and literals)

#punctuators, some example ( { []}), : ; ' " ''' etc

#here im using variable names and literals to explain about fundamental of python on friday 12/05/2023

#Comments-not included in code but give info. about code

a = 4
b = 5
c = True
d = 3+5j
e = None

type(c)

id(b)

'''kwmdoiewjdoew'''#using triple quotes we can bulk the code in comment

a = 5
b = 8.5
c = True
d = None
e = 3 + 4j
type (c)

id(a)

a = 1
def sum(a,b):
  apple = 78

print(sum)