# -*- coding: utf-8 -*-
"""coderready_airline_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/aryanjaswaliit/coder_ready_workshop/blob/master/airline/coderready_airline_analysis.ipynb

# Airline Data Science Operation Day 3
"""

import pandas as pd
import numpy as np
import seaborn as sns

flight = pd.read_csv("/content/airline_data (2).csv")

flight.head()

df1 = flight.copy()

df1.count()

df1.columns

df1.info()

df1.describe()

df1.head()

df1["Year"].value_counts()

df1.isna().sum()

"""## Drop all null column"""

df1.dropna(axis=1, inplace=True)

df1.shape

df1.info()

df1.corr()

"""## Find Delay average by month

"""

flight.head()

delay = flight.groupby("Month")["ArrDelay"].mean()

sns.relplot(x='Month', y='ArrDelay', kind='line', data=flight, height=6, aspect=2, color="blue")